"""OpenAPI export: `docs/openapi.json` (machine-readable) and `docs/API.md` (endpoint table + DTO fields).

`training export-openapi` writes both; a test checks the committed files are current. Output is
deterministic (route order, no timestamps).
"""

import json
from typing import Any

from training.api.main import create_app

SKIPPED_SCHEMAS = ("HTTPValidationError", "ValidationError")
HTTP_METHODS = ("get", "post", "put", "patch", "delete")

INTRO = """\
# API

Generated by `uv run training export-openapi` from the FastAPI app – do not edit by hand.
The machine-readable contract is [openapi.json](openapi.json) (also served at `/openapi.json`, interactive
docs at `/docs`).

- Every path is below `/api`. Request and response bodies are JSON and are exactly the DTOs of
  `backend/training/services/dto.py`, the same objects the Streamlit UI renders.
- Units are internal ones: seconds, metres, m/s, bpm, TSS-equivalent points, local dates as `YYYY-MM-DD`,
  timestamps in UTC. Pace (min/km) and h:mm are formatted by the client.
- Errors are `{"detail": "<message>"}`: 404 not found, 422 invalid parameters or body, 502 Garmin failure
  (login rejected, rate limit, unreachable).
"""


def build_spec() -> dict[str, Any]:
    return create_app().openapi()


def render_openapi_json(spec: dict[str, Any]) -> str:
    return json.dumps(spec, indent=2, ensure_ascii=False) + "\n"


def render_api_md(spec: dict[str, Any]) -> str:
    lines = [INTRO, "## Endpoints", ""]
    lines += ["| Method | Path | Parameters | Response | Summary |", "|---|---|---|---|---|"]
    for path, item in spec["paths"].items():
        for method in HTTP_METHODS:
            op = item.get(method)
            if op is None:
                continue
            cells = [method.upper(), f"`{path}`", _parameters(op), _response(op), op.get("summary", "")]
            lines.append("| " + " | ".join(_cell(c) for c in cells) + " |")
    lines += ["", "## Schemas", ""]
    for name, schema in sorted(spec.get("components", {}).get("schemas", {}).items()):
        if name in SKIPPED_SCHEMAS:
            continue
        lines += [f"### {name}", ""]
        if schema.get("description"):
            lines += [schema["description"], ""]
        required = set(schema.get("required", []))
        lines += ["| Field | Type | Description |", "|---|---|---|"]
        for field, prop in schema.get("properties", {}).items():
            label = f"`{field}`" + ("" if field in required else " (optional)")
            lines.append(
                f"| {_cell(label)} | {_cell(_type_of(prop))} | {_cell(prop.get('description', ''))} |"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _parameters(op: dict[str, Any]) -> str:
    names = [
        f"`{p['name']}`" + ("" if p.get("required") else "?")
        for p in op.get("parameters", [])
        if p["in"] in ("path", "query")
    ]
    body = op.get("requestBody", {}).get("content", {}).get("application/json", {}).get("schema")
    if body:
        names.append(f"body: `{_type_of(body)}`")
    return ", ".join(names) or "–"


def _response(op: dict[str, Any]) -> str:
    schema = op.get("responses", {}).get("200", {}).get("content", {}).get("application/json", {})
    return f"`{_type_of(schema['schema'])}`" if "schema" in schema else "–"


def _type_of(schema: dict[str, Any]) -> str:
    """A compact, TypeScript-like rendering of a JSON schema fragment."""
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in schema:
        return " | ".join(_type_of(s) for s in schema["anyOf"])
    kind = schema.get("type")
    if kind == "array":
        item = _type_of(schema.get("items", {}))
        return f"({item})[]" if " | " in item else f"{item}[]"
    if kind == "object":
        extra = schema.get("additionalProperties")
        return f"map<string, {_type_of(extra)}>" if isinstance(extra, dict) else "object"
    if schema.get("format") in ("date", "date-time"):
        return schema["format"]
    return kind or "any"


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")
