"""initial schema

Revision ID: d0211dc3d94e
Revises: 
Create Date: 2026-09-29 09:15:06.955956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (sqlmodel.sql.sqltypes.AutoString in autogenerated migrations)


# revision identifiers, used by Alembic.
revision: str = 'd0211dc3d94e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garmin_id', sa.Integer(), nullable=False),
    sa.Column('sport', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sub_sport', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_utc', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('tz', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('moving_s', sa.Float(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('elev_gain_m', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Float(), nullable=True),
    sa.Column('max_hr', sa.Float(), nullable=True),
    sa.Column('avg_speed', sa.Float(), nullable=True),
    sa.Column('avg_cadence', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('is_race', sa.Boolean(), nullable=False),
    sa.Column('is_indoor', sa.Boolean(), nullable=False),
    sa.Column('garmin_training_load', sa.Float(), nullable=True),
    sa.Column('garmin_aerobic_te', sa.Float(), nullable=True),
    sa.Column('garmin_anaerobic_te', sa.Float(), nullable=True),
    sa.Column('garmin_vo2max', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_garmin_id'), ['garmin_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_activity_local_date'), ['local_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_sport'), ['sport'], unique=False)

    op.create_table('athlete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Float(), nullable=True),
    sa.Column('rest_hr_override', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('run_bike_split', sa.Float(), nullable=True),
    sa.Column('preferred_days', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curve_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sport', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('curve', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'sport')
    )
    op.create_table('daily_load',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('load_total', sa.Float(), nullable=False),
    sa.Column('load_run', sa.Float(), nullable=False),
    sa.Column('load_bike', sa.Float(), nullable=False),
    sa.Column('ctl', sa.Float(), nullable=True),
    sa.Column('atl', sa.Float(), nullable=True),
    sa.Column('tsb', sa.Float(), nullable=True),
    sa.Column('acwr', sa.Float(), nullable=True),
    sa.Column('monotony', sa.Float(), nullable=True),
    sa.Column('strain', sa.Float(), nullable=True),
    sa.Column('ramp_rate', sa.Float(), nullable=True),
    sa.Column('readiness', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('daily_wellness',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sleep_start', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('sleep_end', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('sleep_s', sa.Float(), nullable=True),
    sa.Column('deep_s', sa.Float(), nullable=True),
    sa.Column('light_s', sa.Float(), nullable=True),
    sa.Column('rem_s', sa.Float(), nullable=True),
    sa.Column('awake_s', sa.Float(), nullable=True),
    sa.Column('sleep_score', sa.Float(), nullable=True),
    sa.Column('rhr', sa.Float(), nullable=True),
    sa.Column('body_battery_wake', sa.Float(), nullable=True),
    sa.Column('body_battery_min', sa.Float(), nullable=True),
    sa.Column('stress_avg', sa.Float(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('target_time_s', sa.Float(), nullable=True),
    sa.Column('sport', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_garmin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ref_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fetched_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('payload_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'ref_key')
    )
    with op.batch_alter_table('raw_garmin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_garmin_kind'), ['kind'], unique=False)

    op.create_table('sync_state',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('threshold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('lthr', sa.Float(), nullable=True),
    sa.Column('threshold_speed', sa.Float(), nullable=True),
    sa.Column('zones', sa.JSON(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport', 'valid_from')
    )
    with op.batch_alter_table('threshold', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threshold_sport'), ['sport'], unique=False)

    op.create_table('activity_metric',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('load_primary', sa.Float(), nullable=True),
    sa.Column('load_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hrtss', sa.Float(), nullable=True),
    sa.Column('trimp_norm', sa.Float(), nullable=True),
    sa.Column('rtss', sa.Float(), nullable=True),
    sa.Column('if_hr', sa.Float(), nullable=True),
    sa.Column('if_pace', sa.Float(), nullable=True),
    sa.Column('hr_coverage', sa.Float(), nullable=True),
    sa.Column('low_confidence', sa.Boolean(), nullable=False),
    sa.Column('time_in_hr_zone', sa.JSON(), nullable=True),
    sa.Column('time_in_pace_zone', sa.JSON(), nullable=True),
    sa.Column('steady_state', sa.Boolean(), nullable=True),
    sa.Column('ef', sa.Float(), nullable=True),
    sa.Column('decoupling_pct', sa.Float(), nullable=True),
    sa.Column('pace_at_ref_hr_day', sa.Float(), nullable=True),
    sa.Column('threshold_id_used', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threshold_id_used'], ['threshold.id'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_table('activity_stream',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('t', sa.Integer(), nullable=False),
    sa.Column('hr', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('gap_speed', sa.Float(), nullable=True),
    sa.Column('alt', sa.Float(), nullable=True),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('cadence', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('moving', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id', 't')
    )
    op.create_table('best_effort',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('sport', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('window_s', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'kind', 'window_s')
    )
    with op.batch_alter_table('best_effort', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_best_effort_activity_id'), ['activity_id'], unique=False)

    op.create_table('planned_workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sport', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('structure', sa.JSON(), nullable=True),
    sa.Column('estimated_load', sa.Float(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('garmin_workout_id', sa.Integer(), nullable=True),
    sa.Column('completed_activity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['completed_activity_id'], ['activity.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planned_workout', schema=None) as batch_op:
        batch_op.create_index('ix_planned_workout_date_sport', ['date', 'sport'], unique=False)

    op.create_table('subjective',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('rpe', sa.Integer(), nullable=True),
    sa.Column('feel', sa.Integer(), nullable=True),
    sa.Column('soreness', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subjective', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjective_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjective', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjective_date'))

    op.drop_table('subjective')
    with op.batch_alter_table('planned_workout', schema=None) as batch_op:
        batch_op.drop_index('ix_planned_workout_date_sport')

    op.drop_table('planned_workout')
    with op.batch_alter_table('best_effort', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_best_effort_activity_id'))

    op.drop_table('best_effort')
    op.drop_table('activity_stream')
    op.drop_table('activity_metric')
    with op.batch_alter_table('threshold', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threshold_sport'))

    op.drop_table('threshold')
    op.drop_table('sync_state')
    with op.batch_alter_table('raw_garmin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_garmin_kind'))

    op.drop_table('raw_garmin')
    op.drop_table('goal')
    op.drop_table('daily_wellness')
    op.drop_table('daily_load')
    op.drop_table('curve_snapshot')
    op.drop_table('athlete')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_sport'))
        batch_op.drop_index(batch_op.f('ix_activity_local_date'))
        batch_op.drop_index(batch_op.f('ix_activity_garmin_id'))

    op.drop_table('activity')
    # ### end Alembic commands ###
