"""subjective unique activity

Revision ID: 144d0b830479
Revises: d0211dc3d94e
Create Date: 2026-09-29 11:09:21.749845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (sqlmodel.sql.sqltypes.AutoString in autogenerated migrations)


# revision identifiers, used by Alembic.
revision: str = '144d0b830479'
down_revision: Union[str, Sequence[str], None] = 'd0211dc3d94e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjective', schema=None) as batch_op:
        batch_op.create_index('ux_subjective_activity_id', ['activity_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjective', schema=None) as batch_op:
        batch_op.drop_index('ux_subjective_activity_id')

    # ### end Alembic commands ###
