"""best effort distance

Revision ID: 643693e83815
Revises: 144d0b830479
Create Date: 2026-09-29 11:38:06.933915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (sqlmodel.sql.sqltypes.AutoString in autogenerated migrations)


# revision identifiers, used by Alembic.
revision: str = '643693e83815'
down_revision: Union[str, Sequence[str], None] = '144d0b830479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('best_effort', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('start_t', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('best_effort', schema=None) as batch_op:
        batch_op.drop_column('start_t')
        batch_op.drop_column('distance_m')

    # ### end Alembic commands ###
